name = "gg"
license = "MIT"
licenselink = "https://git.sr.ht/~gg/blog-theme/tree/master/item/LICENSE"
description = "Simple theme that hides content when JS is enabled"
homepage = "https://git.sr.ht/~gg/blog-theme"
demosite = "https://www.gclv.es"
tags = ["blog", "plain", "blank", "starter", "development", "noscript"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "gclv"
  homepage = "https://gclv.es"
